### ISSUE TITLE
add windows support

### ISSUE THREAD

**Issue by jlegewie** [jlegewie/SublimePeek#4]
sublime.platform(): Returns the platform, which may be "osx", "linux" or "windows"

**Comment by miguelhughes** [comment]
I'm interested in having this under windows too! I think this is a great plugin and I miss having documentation inside the IDE, compared to other IDES this bridges that batch very nicely! I see these comments are a bit old. Are you interested in rekindeling this?

I ran it on windows using st3 and it runs, partially:
- On one end: the inline help is not inline, but opens a browser. I'm ok with that, as the quick access and having it locally is more than enough.
- On the other end, it seems that the help files I need were not entirely compiled. I use php, and  some basic functions are not there, such as "mysql_num_rows" or "isset". Here is the output:
  
  Exception in thread Thread-6:
  Traceback (most recent call last):
    File "./threading.py", line 901, in _bootstrap_inner
    File "C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\SublimePeek\SublimePeek.py", line 689, in run
      f = open(os.path.join(self.path, id + ".html"), "wb")
  OSError: [Errno 22] Invalid argument: 'C:\Users\Miguel\AppData\Roaming\Sublime Text 3\Packages\SublimePeek-PHP-help\HttpDeflateStream::__construct.html'

Any suggestions?

**Comment by jlegewie** [comment]
I am not going to put any major work into this right now but I am happy when others send pull requests. 
By the way, you can now get the help as a tooltip. Just use the `show_popup` option. It's not perfect because the full html is converted to ST's mini html. Personally, I also use the `Source Code Pro` font, which make the tooltip look much better (see my css file below). I hope that in the future ST3 will provide an API for the new release note window (try it be clicking on "Sublime Text -> Changelog"). I think that would be the optimal solution without any external dependencies.

```
body {
    font-family: "Source Code Pro Light";
    color: #444444;
}
h1, h2 {
    font-family: "Source Code Pro Light";
    font-weight: Regular;
    color: #444444;
    font-size: 1.4em;
}
h3 {
    font-family: "Source Code Pro Semibold";
    color: #444444;
    font-size: 1.2em;
}
h4 {
    font-family: "Source Code Pro Medium";
    color: #444444;
    font-size: 1.2em;
}
.code {
    font-family: "Source Code Pro";
    background-color: #F2F2F2;
    color: #000000;
}
.pre {
    font-family: "Source Code Pro";
    display: block;
    background-color: #F6F6F6;
    color: #000000;
}
```

**Comment by miguelhughes** [comment]
Thanks! Now I see it inside ST, this is awesome!
I tried your css and it looks nicer now. It corresponds in SublimePeek/css/tooltip.css, right?

Is there any chance you can provide any feedback on what could be causing the error above? Or maybe you can post a compiled php doc as you did for "R"? Or I could try and build it myself externally but it looks like the compiler doesn't work ok on windows.

**Comment by jlegewie** [comment]
There is some discussion about that problem in earlier posts in the threat. Windows is not happy with the filename `HttpDeflateStream::__construct.html`. I never got around to fix that. The compiled php docs won't help because they would include filenames that are invalid for windows. Feel free to give it a shot!

**Comment by miguelhughes** [comment]
Ok, thanks man. I'll post here if I make any progress

**Comment by miguelhughes** [comment]
cmartinfosol's fix worked for fixing the help file compile error. May 22, 2012. I understand it's not a good idea because those help files won't be found, but at least I get most of the functions I normally use documented.
Maybe I'll chip in in the future when I'm more familiarized with python, I'd love to help, this is so close to working on windows...
